### PR TITLE
[WIP] Fix incorrect uncompressed dataset

### PR DESCRIPTION
**Pull request by scaramallion**
#### Describe the changes
Updates US1_UNCI.dcm with the correct uncompressed pixel data

#### Tasks
- [x] In a branch on your fork of *pydicom-data*, add or modify data files
- [x] Create a pull request for *pydicom-data*
- [ ] Update the commit hash for the urls in a fork/branch of the *pydicom* file `[urls.json]https://github.com/pydicom/pydicom/blob/master/pydicom/data/urls.json` and create a *pydicom* pull request 
- [ ] *pydicom* unit tests passing

### CODE REVIEW

**Comment by scaramallion** [comment]
I'm a little confused how this works now, the pydicom unit tests should still pass because the download URL refers to a particular commit? Should the urls.json file be after after this is merged?

**Comment by darcymason** [comment]
> I'm a little confused how this works now, the pydicom unit tests should still pass because the download URL refers to a particular commit? Should the urls.json file be updated after this is merged or do you want a paired PR so both are available to be merged (presumably after this one is merged the other has its actions run with the updated -data then merged)?

I'm still kind of working through this too, but I think everything you said is right.  We can commit here first without affecting previous pydicom because it has the exact commit hash (not the new one from this PR).  Then update the pydicom urls.json (replace-all of the old commit hash with the new one from this PR) -- only pydicom tests associated with files changed in this PR will be affected in pydicom, all others unchanged between commits.

**Comment by scaramallion** [comment]
Sorry, I updated things while you were answering:

> Although, won't I only know the commit hash after the squash + merge?

Looking at the master history a new hash is generated on merge

**Comment by darcymason** [comment]
> Looking at the master history a new hash is generated on squash + merge

Right, so I should update the PR template again to be a little more specific about that, and the checklist isn't really completed here, so maybe separate into two checklists- pre and post merge here.

Are you ready to merge this now?  I'm not sure of rights on this one, you should probably have them.  And looks like does not require official review, which I think is fine.

**Comment by darcymason** [comment]
I'm knocking off for the night - I'll pick up on anything else needed from me tomorrow.

**Comment by scaramallion** [comment]
Yep its ready

**Comment by darcymason** [comment]
Hmmm... it says you've merged it into master but I'm still see the Merge button on github ... ? I'll just close the PR as it looks like the correct commit url is used in pydicom.

**Pull request merged**
