### PR TITLE
[MRG] Correct Big Endian test files

### PR DESCRIPTION
**Pull request by mrbean-bremen**
- see PR [pydicom#1687](https://github.com/pydicom/pydicom/pull/1687)
- recreated the files from Little Endian using `dcmconv -tb`

#### Tasks
- [x] In a branch on your fork of *pydicom-data*, add or modify data files
- [x] Create a pull request for *pydicom-data*  <-- just doing this 😀 - maybe we can remove this from the template
- [x] Update the commit hash for the urls in a fork/branch of the *pydicom* file `[urls.json]https://github.com/pydicom/pydicom/blob/master/pydicom/data/urls.json` and create a *pydicom* pull request 
- [ ] *pydicom* unit tests passing
- [ ] Documentation updated (if needed) - n.a.

### CODE REVIEW

**Comment by mrbean-bremen** [comment]
Ok, I think I have to use the master branch for the PR, otherwise the commit hash won't work...

**Comment by mrbean-bremen** [comment]
@darcymason - I think this won't work as described in the PR template, at least I can't get it to work. Probably need to merge this first and update the commit hash in `pydicom` afterwards.

**Comment by darcymason** [comment]
> @darcymason - I think this won't work as described in the PR template, at least I can't get it to work. Probably need to merge this first and update the commit hash in pydicom afterwards.

I'm not clear on what the problem is. but I'm happy to do it that way. If a straight merge is used, the commit hash should stay intact, but in any case after commiting here we will know for sure what it is.

However, I thought I would give a little more time first before merging this, for @scaramallion's take as requested in #1687...

**Comment by mrbean-bremen** [comment]
> I'm not clear on what the problem is. but I'm happy to do it that way. If a straight merge is used, the commit hash should stay intact, but in any case after commiting here we will know for sure what it is.

The problem is probably that the commit is in my own fork, not in the main repo, so this may be a permission problem. I'm not sure how permissions between forks work in this case. But maybe I'm just doing something wrong...

> However, I thought I would give a little more time first before merging this, for @scaramallion's take as requested in #1687...

Sure, of course!

**Comment by mrbean-bremen** [comment]
> If a straight merge is used, the commit hash should stay intact, but in any case after commiting here we will know for sure what it is.

FWIW, I just verified that this is not the case between forks - I merged a PR in another repo via rebase, and the resulting commit has a different commit hash than the one in the PR. I didn't think that this would work between different repositories (e.g. forks) anyway.

**Pull request merged**
